### PR TITLE
PULL request about issues speed up

### PR DESCRIPTION
**Pull request by wuchangsheng951**
This pull request is about to implement the speedup mentioned in this issue https://github.com/Rudrabha/Wav2Lip/issues/263
I test on my custom dataset, and the results show that it does speed up more than 10x times.
But I have no idea if adding this shared dict will cause memory overflow.

### CODE REVIEW

**Comment by FrischJulien** [comment]
thanks for sharing this

**Comment by GzuPark** [comment]
@wuchangsheng951 As you mentioned, this PR will be overflowed depends on the dataset size.

**Comment by prajwalkr** [comment]
Closing because it will not scale easily to large datasets.

**Comment by hannarud** [comment]
Speedup with no additional space required can be done by saving audios to numpy arrays, I created a pull request here: https://github.com/Rudrabha/Wav2Lip/pull/420

**Pull request closed without merging**
