### PR TITLE
fix face detection failure on video with titles / fade-in / fade-out

### PR DESCRIPTION
**Pull request by eyaler**
when using face_detection on video, ignore any frames before that first one containing a face, and ignore any frames from the first instance after that where detection fails. this allows dealing with the common use case of videos that start with titles or fade in or end with titles or fade out (the latter would be an issue when the audio is longer than the video). i tested this in the following cases:
1. image without face
2. image without face with box argument
3. video without face
4. video without face with box argument
5. video beginning with fade in from black, then having a face, then fade out to black  + audio that is longer than video

### CODE REVIEW

**Comment by prajwalkr** [comment]
Hello, thank you for your contribution. I have one question: If you change the number of output frames, you should also trim the audio accordingly right? Otherwise, if you overlay the original audio, then the lips will be out of sync as the frames have changed.

**Comment by eyaler** [comment]
@prajwalkr i did not consider the use case of having a synced audio and video to begin with. i guess in this case when you have voice but no face showing, you would actually want to keep these frames in without applying wav2lip (as there is no face) - "pass" strategy. but for the more general case of different video and audio, i think what i am doing is consistent with the "audio first" approach as originally implemented, that is, trim video if longer than audio, or loop video if shorter than audio. so my idea here was just to extract the usable frames. although one could argue that (1) if you have partially faded frames - this is not what you want anyway (2) the pass frames strategy could also make sense in the general use case (especially if the video is not looping). (3) the pass strategy could also be useful for intermediate frames without face (e.g. occlusion) which i do not currently take care of - I "break" to end the video there and allow it to loop, but you could alternatively either just "cut" the frames until the next face or "pass" and leave in the unprocessed frames. please note that my change addresses the case where the code would otherwise return an error. but on top of that you could consider offering several options: (1) "cut" or "pass" for the beginning. (2) "cut" or "pass" or "break" for intermediate faceless frames. (3) "cut" or "pass" for the ending (relevant if 2!=break). my implementation is for 1=cut and 2=break. sorry for overly long answer.

**Comment by prajwalkr** [comment]
Have you tested on such videos where there is titles at the start and some effects at the end where the face is absent? Can you post some results here?

**Comment by eyaler** [comment]
i tested with fade in from black and fade out to black

**Comment by prajwalkr** [comment]
Can you post some results here?

**Comment by prajwalkr** [comment]
Re-open if necessary

**Pull request closed without merging**
